#!/usr/bin/python3
def raise_exception():
    n = 1
    for i in n:
        continue
